ARG VERSION=11.5.2

FROM grafana/grafana-oss:${VERSION}

# copy the datasources and dashboards provisioning
COPY datasources /etc/grafana/provisioning/datasources
COPY dashboards/dashboards.yml /etc/grafana/provisioning/dashboards/
COPY dashboards/*.json /etc/grafana/dashboards/
